// Code generated by translation from Zig - manual edits will be overwritten.

import { Type, Types, createTypes } from "./types";

/**
 * Representation of a Generation I Pokémon species.
 */
export enum Species {
  None = 0,
  Bulbasaur = 1,
  Ivysaur = 2,
  Venusaur = 3,
  Charmander = 4,
  Charmeleon = 5,
  Charizard = 6,
  Squirtle = 7,
  Wartortle = 8,
  Blastoise = 9,
  Caterpie = 10,
  Metapod = 11,
  Butterfree = 12,
  Weedle = 13,
  Kakuna = 14,
  Beedrill = 15,
  Pidgey = 16,
  Pidgeotto = 17,
  Pidgeot = 18,
  Rattata = 19,
  Raticate = 20,
  Spearow = 21,
  Fearow = 22,
  Ekans = 23,
  Arbok = 24,
  Pikachu = 25,
  Raichu = 26,
  Sandshrew = 27,
  Sandslash = 28,
  NidoranF = 29,
  Nidorina = 30,
  Nidoqueen = 31,
  NidoranM = 32,
  Nidorino = 33,
  Nidoking = 34,
  Clefairy = 35,
  Clefable = 36,
  Vulpix = 37,
  Ninetales = 38,
  Jigglypuff = 39,
  Wigglytuff = 40,
  Zubat = 41,
  Golbat = 42,
  Oddish = 43,
  Gloom = 44,
  Vileplume = 45,
  Paras = 46,
  Parasect = 47,
  Venonat = 48,
  Venomoth = 49,
  Diglett = 50,
  Dugtrio = 51,
  Meowth = 52,
  Persian = 53,
  Psyduck = 54,
  Golduck = 55,
  Mankey = 56,
  Primeape = 57,
  Growlithe = 58,
  Arcanine = 59,
  Poliwag = 60,
  Poliwhirl = 61,
  Poliwrath = 62,
  Abra = 63,
  Kadabra = 64,
  Alakazam = 65,
  Machop = 66,
  Machoke = 67,
  Machamp = 68,
  Bellsprout = 69,
  Weepinbell = 70,
  Victreebel = 71,
  Tentacool = 72,
  Tentacruel = 73,
  Geodude = 74,
  Graveler = 75,
  Golem = 76,
  Ponyta = 77,
  Rapidash = 78,
  Slowpoke = 79,
  Slowbro = 80,
  Magnemite = 81,
  Magneton = 82,
  Farfetchd = 83,
  Doduo = 84,
  Dodrio = 85,
  Seel = 86,
  Dewgong = 87,
  Grimer = 88,
  Muk = 89,
  Shellder = 90,
  Cloyster = 91,
  Gastly = 92,
  Haunter = 93,
  Gengar = 94,
  Onix = 95,
  Drowzee = 96,
  Hypno = 97,
  Krabby = 98,
  Kingler = 99,
  Voltorb = 100,
  Electrode = 101,
  Exeggcute = 102,
  Exeggutor = 103,
  Cubone = 104,
  Marowak = 105,
  Hitmonlee = 106,
  Hitmonchan = 107,
  Lickitung = 108,
  Koffing = 109,
  Weezing = 110,
  Rhyhorn = 111,
  Rhydon = 112,
  Chansey = 113,
  Tangela = 114,
  Kangaskhan = 115,
  Horsea = 116,
  Seadra = 117,
  Goldeen = 118,
  Seaking = 119,
  Staryu = 120,
  Starmie = 121,
  MrMime = 122,
  Scyther = 123,
  Jynx = 124,
  Electabuzz = 125,
  Magmar = 126,
  Pinsir = 127,
  Tauros = 128,
  Magikarp = 129,
  Gyarados = 130,
  Lapras = 131,
  Ditto = 132,
  Eevee = 133,
  Vaporeon = 134,
  Jolteon = 135,
  Flareon = 136,
  Porygon = 137,
  Omanyte = 138,
  Omastar = 139,
  Kabuto = 140,
  Kabutops = 141,
  Aerodactyl = 142,
  Snorlax = 143,
  Articuno = 144,
  Zapdos = 145,
  Moltres = 146,
  Dratini = 147,
  Dragonair = 148,
  Dragonite = 149,
  Mewtwo = 150,
  Mew = 151,
}

const CHANCES: number[] = [
  22, // Bulbasaur
  30, // Ivysaur
  40, // Venusaur
  32, // Charmander
  40, // Charmeleon
  50, // Charizard
  21, // Squirtle
  29, // Wartortle
  39, // Blastoise
  22, // Caterpie
  15, // Metapod
  35, // Butterfree
  25, // Weedle
  17, // Kakuna
  37, // Beedrill
  28, // Pidgey
  35, // Pidgeotto
  45, // Pidgeot
  36, // Rattata
  48, // Raticate
  35, // Spearow
  50, // Fearow
  27, // Ekans
  40, // Arbok
  45, // Pikachu
  50, // Raichu
  20, // Sandshrew
  32, // Sandslash
  20, // NidoranF
  28, // Nidorina
  38, // Nidoqueen
  25, // NidoranM
  32, // Nidorino
  42, // Nidoking
  17, // Clefairy
  30, // Clefable
  32, // Vulpix
  50, // Ninetales
  10, // Jigglypuff
  22, // Wigglytuff
  27, // Zubat
  45, // Golbat
  15, // Oddish
  20, // Gloom
  25, // Vileplume
  12, // Paras
  15, // Parasect
  22, // Venonat
  45, // Venomoth
  47, // Diglett
  60, // Dugtrio
  45, // Meowth
  57, // Persian
  27, // Psyduck
  42, // Golduck
  35, // Mankey
  47, // Primeape
  30, // Growlithe
  47, // Arcanine
  45, // Poliwag
  45, // Poliwhirl
  35, // Poliwrath
  45, // Abra
  52, // Kadabra
  60, // Alakazam
  17, // Machop
  22, // Machoke
  27, // Machamp
  20, // Bellsprout
  27, // Weepinbell
  35, // Victreebel
  35, // Tentacool
  50, // Tentacruel
  10, // Geodude
  17, // Graveler
  22, // Golem
  45, // Ponyta
  52, // Rapidash
  7, // Slowpoke
  15, // Slowbro
  22, // Magnemite
  35, // Magneton
  30, // Farfetchd
  37, // Doduo
  50, // Dodrio
  22, // Seel
  35, // Dewgong
  12, // Grimer
  25, // Muk
  20, // Shellder
  35, // Cloyster
  40, // Gastly
  47, // Haunter
  55, // Gengar
  35, // Onix
  21, // Drowzee
  33, // Hypno
  25, // Krabby
  37, // Kingler
  50, // Voltorb
  70, // Electrode
  20, // Exeggcute
  27, // Exeggutor
  17, // Cubone
  22, // Marowak
  43, // Hitmonlee
  38, // Hitmonchan
  15, // Lickitung
  17, // Koffing
  30, // Weezing
  12, // Rhyhorn
  20, // Rhydon
  25, // Chansey
  30, // Tangela
  45, // Kangaskhan
  30, // Horsea
  42, // Seadra
  31, // Goldeen
  34, // Seaking
  42, // Staryu
  57, // Starmie
  45, // MrMime
  52, // Scyther
  47, // Jynx
  52, // Electabuzz
  46, // Magmar
  42, // Pinsir
  55, // Tauros
  40, // Magikarp
  40, // Gyarados
  30, // Lapras
  24, // Ditto
  27, // Eevee
  32, // Vaporeon
  65, // Jolteon
  32, // Flareon
  20, // Porygon
  17, // Omanyte
  27, // Omastar
  27, // Kabuto
  40, // Kabutops
  65, // Aerodactyl
  15, // Snorlax
  42, // Articuno
  50, // Zapdos
  45, // Moltres
  25, // Dratini
  35, // Dragonair
  40, // Dragonite
  65, // Mewtwo
  50, // Mew
];

/**
 * Stats for a Pokémon species.
 */
export interface Stats {
  hp: number;
  atk: number;
  def: number;
  spe: number;
  spc: number;
}

/**
 * Data associated with a Pokémon species.
 */
export interface SpeciesData {
  stats: Stats;
  types: Types;
}

const DATA: SpeciesData[] = [
  // Bulbasaur
  {
    stats: { hp: 45, atk: 49, def: 49, spe: 45, spc: 65 },
    types: createTypes(Type.Grass, Type.Poison),
  },
  // Ivysaur
  {
    stats: { hp: 60, atk: 62, def: 63, spe: 60, spc: 80 },
    types: createTypes(Type.Grass, Type.Poison),
  },
  // Venusaur
  {
    stats: { hp: 80, atk: 82, def: 83, spe: 80, spc: 100 },
    types: createTypes(Type.Grass, Type.Poison),
  },
  // Charmander
  {
    stats: { hp: 39, atk: 52, def: 43, spe: 65, spc: 50 },
    types: createTypes(Type.Fire, Type.Fire),
  },
  // Charmeleon
  {
    stats: { hp: 58, atk: 64, def: 58, spe: 80, spc: 65 },
    types: createTypes(Type.Fire, Type.Fire),
  },
  // Charizard
  {
    stats: { hp: 78, atk: 84, def: 78, spe: 100, spc: 85 },
    types: createTypes(Type.Fire, Type.Flying),
  },
  // Squirtle
  {
    stats: { hp: 44, atk: 48, def: 65, spe: 43, spc: 50 },
    types: createTypes(Type.Water, Type.Water),
  },
  // Wartortle
  {
    stats: { hp: 59, atk: 63, def: 80, spe: 58, spc: 65 },
    types: createTypes(Type.Water, Type.Water),
  },
  // Blastoise
  {
    stats: { hp: 79, atk: 83, def: 100, spe: 78, spc: 85 },
    types: createTypes(Type.Water, Type.Water),
  },
  // Caterpie
  {
    stats: { hp: 45, atk: 30, def: 35, spe: 45, spc: 20 },
    types: createTypes(Type.Bug, Type.Bug),
  },
  // Metapod
  {
    stats: { hp: 50, atk: 20, def: 55, spe: 30, spc: 25 },
    types: createTypes(Type.Bug, Type.Bug),
  },
  // Butterfree
  {
    stats: { hp: 60, atk: 45, def: 50, spe: 70, spc: 80 },
    types: createTypes(Type.Bug, Type.Flying),
  },
  // Weedle
  {
    stats: { hp: 40, atk: 35, def: 30, spe: 50, spc: 20 },
    types: createTypes(Type.Bug, Type.Poison),
  },
  // Kakuna
  {
    stats: { hp: 45, atk: 25, def: 50, spe: 35, spc: 25 },
    types: createTypes(Type.Bug, Type.Poison),
  },
  // Beedrill
  {
    stats: { hp: 65, atk: 80, def: 40, spe: 75, spc: 45 },
    types: createTypes(Type.Bug, Type.Poison),
  },
  // Pidgey
  {
    stats: { hp: 40, atk: 45, def: 40, spe: 56, spc: 35 },
    types: createTypes(Type.Normal, Type.Flying),
  },
  // Pidgeotto
  {
    stats: { hp: 63, atk: 60, def: 55, spe: 71, spc: 50 },
    types: createTypes(Type.Normal, Type.Flying),
  },
  // Pidgeot
  {
    stats: { hp: 83, atk: 80, def: 75, spe: 91, spc: 70 },
    types: createTypes(Type.Normal, Type.Flying),
  },
  // Rattata
  {
    stats: { hp: 30, atk: 56, def: 35, spe: 72, spc: 25 },
    types: createTypes(Type.Normal, Type.Normal),
  },
  // Raticate
  {
    stats: { hp: 55, atk: 81, def: 60, spe: 97, spc: 50 },
    types: createTypes(Type.Normal, Type.Normal),
  },
  // Spearow
  {
    stats: { hp: 40, atk: 60, def: 30, spe: 70, spc: 31 },
    types: createTypes(Type.Normal, Type.Flying),
  },
  // Fearow
  {
    stats: { hp: 65, atk: 90, def: 65, spe: 100, spc: 61 },
    types: createTypes(Type.Normal, Type.Flying),
  },
  // Ekans
  {
    stats: { hp: 35, atk: 60, def: 44, spe: 55, spc: 40 },
    types: createTypes(Type.Poison, Type.Poison),
  },
  // Arbok
  {
    stats: { hp: 60, atk: 85, def: 69, spe: 80, spc: 65 },
    types: createTypes(Type.Poison, Type.Poison),
  },
  // Pikachu
  {
    stats: { hp: 35, atk: 55, def: 30, spe: 90, spc: 50 },
    types: createTypes(Type.Electric, Type.Electric),
  },
  // Raichu
  {
    stats: { hp: 60, atk: 90, def: 55, spe: 100, spc: 90 },
    types: createTypes(Type.Electric, Type.Electric),
  },
  // Sandshrew
  {
    stats: { hp: 50, atk: 75, def: 85, spe: 40, spc: 30 },
    types: createTypes(Type.Ground, Type.Ground),
  },
  // Sandslash
  {
    stats: { hp: 75, atk: 100, def: 110, spe: 65, spc: 55 },
    types: createTypes(Type.Ground, Type.Ground),
  },
  // NidoranF
  {
    stats: { hp: 55, atk: 47, def: 52, spe: 41, spc: 40 },
    types: createTypes(Type.Poison, Type.Poison),
  },
  // Nidorina
  {
    stats: { hp: 70, atk: 62, def: 67, spe: 56, spc: 55 },
    types: createTypes(Type.Poison, Type.Poison),
  },
  // Nidoqueen
  {
    stats: { hp: 90, atk: 82, def: 87, spe: 76, spc: 75 },
    types: createTypes(Type.Poison, Type.Ground),
  },
  // NidoranM
  {
    stats: { hp: 46, atk: 57, def: 40, spe: 50, spc: 40 },
    types: createTypes(Type.Poison, Type.Poison),
  },
  // Nidorino
  {
    stats: { hp: 61, atk: 72, def: 57, spe: 65, spc: 55 },
    types: createTypes(Type.Poison, Type.Poison),
  },
  // Nidoking
  {
    stats: { hp: 81, atk: 92, def: 77, spe: 85, spc: 75 },
    types: createTypes(Type.Poison, Type.Ground),
  },
  // Clefairy
  {
    stats: { hp: 70, atk: 45, def: 48, spe: 35, spc: 60 },
    types: createTypes(Type.Normal, Type.Normal),
  },
  // Clefable
  {
    stats: { hp: 95, atk: 70, def: 73, spe: 60, spc: 85 },
    types: createTypes(Type.Normal, Type.Normal),
  },
  // Vulpix
  {
    stats: { hp: 38, atk: 41, def: 40, spe: 65, spc: 65 },
    types: createTypes(Type.Fire, Type.Fire),
  },
  // Ninetales
  {
    stats: { hp: 73, atk: 76, def: 75, spe: 100, spc: 100 },
    types: createTypes(Type.Fire, Type.Fire),
  },
  // Jigglypuff
  {
    stats: { hp: 115, atk: 45, def: 20, spe: 20, spc: 25 },
    types: createTypes(Type.Normal, Type.Normal),
  },
  // Wigglytuff
  {
    stats: { hp: 140, atk: 70, def: 45, spe: 45, spc: 50 },
    types: createTypes(Type.Normal, Type.Normal),
  },
  // Zubat
  {
    stats: { hp: 40, atk: 45, def: 35, spe: 55, spc: 40 },
    types: createTypes(Type.Poison, Type.Flying),
  },
  // Golbat
  {
    stats: { hp: 75, atk: 80, def: 70, spe: 90, spc: 75 },
    types: createTypes(Type.Poison, Type.Flying),
  },
  // Oddish
  {
    stats: { hp: 45, atk: 50, def: 55, spe: 30, spc: 75 },
    types: createTypes(Type.Grass, Type.Poison),
  },
  // Gloom
  {
    stats: { hp: 60, atk: 65, def: 70, spe: 40, spc: 85 },
    types: createTypes(Type.Grass, Type.Poison),
  },
  // Vileplume
  {
    stats: { hp: 75, atk: 80, def: 85, spe: 50, spc: 100 },
    types: createTypes(Type.Grass, Type.Poison),
  },
  // Paras
  {
    stats: { hp: 35, atk: 70, def: 55, spe: 25, spc: 55 },
    types: createTypes(Type.Bug, Type.Grass),
  },
  // Parasect
  {
    stats: { hp: 60, atk: 95, def: 80, spe: 30, spc: 80 },
    types: createTypes(Type.Bug, Type.Grass),
  },
  // Venonat
  {
    stats: { hp: 60, atk: 55, def: 50, spe: 45, spc: 40 },
    types: createTypes(Type.Bug, Type.Poison),
  },
  // Venomoth
  {
    stats: { hp: 70, atk: 65, def: 60, spe: 90, spc: 90 },
    types: createTypes(Type.Bug, Type.Poison),
  },
  // Diglett
  {
    stats: { hp: 10, atk: 55, def: 25, spe: 95, spc: 45 },
    types: createTypes(Type.Ground, Type.Ground),
  },
  // Dugtrio
  {
    stats: { hp: 35, atk: 80, def: 50, spe: 120, spc: 70 },
    types: createTypes(Type.Ground, Type.Ground),
  },
  // Meowth
  {
    stats: { hp: 40, atk: 45, def: 35, spe: 90, spc: 40 },
    types: createTypes(Type.Normal, Type.Normal),
  },
  // Persian
  {
    stats: { hp: 65, atk: 70, def: 60, spe: 115, spc: 65 },
    types: createTypes(Type.Normal, Type.Normal),
  },
  // Psyduck
  {
    stats: { hp: 50, atk: 52, def: 48, spe: 55, spc: 50 },
    types: createTypes(Type.Water, Type.Water),
  },
  // Golduck
  {
    stats: { hp: 80, atk: 82, def: 78, spe: 85, spc: 80 },
    types: createTypes(Type.Water, Type.Water),
  },
  // Mankey
  {
    stats: { hp: 40, atk: 80, def: 35, spe: 70, spc: 35 },
    types: createTypes(Type.Fighting, Type.Fighting),
  },
  // Primeape
  {
    stats: { hp: 65, atk: 105, def: 60, spe: 95, spc: 60 },
    types: createTypes(Type.Fighting, Type.Fighting),
  },
  // Growlithe
  {
    stats: { hp: 55, atk: 70, def: 45, spe: 60, spc: 50 },
    types: createTypes(Type.Fire, Type.Fire),
  },
  // Arcanine
  {
    stats: { hp: 90, atk: 110, def: 80, spe: 95, spc: 80 },
    types: createTypes(Type.Fire, Type.Fire),
  },
  // Poliwag
  {
    stats: { hp: 40, atk: 50, def: 40, spe: 90, spc: 40 },
    types: createTypes(Type.Water, Type.Water),
  },
  // Poliwhirl
  {
    stats: { hp: 65, atk: 65, def: 65, spe: 90, spc: 50 },
    types: createTypes(Type.Water, Type.Water),
  },
  // Poliwrath
  {
    stats: { hp: 90, atk: 85, def: 95, spe: 70, spc: 70 },
    types: createTypes(Type.Water, Type.Fighting),
  },
  // Abra
  {
    stats: { hp: 25, atk: 20, def: 15, spe: 90, spc: 105 },
    types: createTypes(Type.Psychic, Type.Psychic),
  },
  // Kadabra
  {
    stats: { hp: 40, atk: 35, def: 30, spe: 105, spc: 120 },
    types: createTypes(Type.Psychic, Type.Psychic),
  },
  // Alakazam
  {
    stats: { hp: 55, atk: 50, def: 45, spe: 120, spc: 135 },
    types: createTypes(Type.Psychic, Type.Psychic),
  },
  // Machop
  {
    stats: { hp: 70, atk: 80, def: 50, spe: 35, spc: 35 },
    types: createTypes(Type.Fighting, Type.Fighting),
  },
  // Machoke
  {
    stats: { hp: 80, atk: 100, def: 70, spe: 45, spc: 50 },
    types: createTypes(Type.Fighting, Type.Fighting),
  },
  // Machamp
  {
    stats: { hp: 90, atk: 130, def: 80, spe: 55, spc: 65 },
    types: createTypes(Type.Fighting, Type.Fighting),
  },
  // Bellsprout
  {
    stats: { hp: 50, atk: 75, def: 35, spe: 40, spc: 70 },
    types: createTypes(Type.Grass, Type.Poison),
  },
  // Weepinbell
  {
    stats: { hp: 65, atk: 90, def: 50, spe: 55, spc: 85 },
    types: createTypes(Type.Grass, Type.Poison),
  },
  // Victreebel
  {
    stats: { hp: 80, atk: 105, def: 65, spe: 70, spc: 100 },
    types: createTypes(Type.Grass, Type.Poison),
  },
  // Tentacool
  {
    stats: { hp: 40, atk: 40, def: 35, spe: 70, spc: 100 },
    types: createTypes(Type.Water, Type.Poison),
  },
  // Tentacruel
  {
    stats: { hp: 80, atk: 70, def: 65, spe: 100, spc: 120 },
    types: createTypes(Type.Water, Type.Poison),
  },
  // Geodude
  {
    stats: { hp: 40, atk: 80, def: 100, spe: 20, spc: 30 },
    types: createTypes(Type.Rock, Type.Ground),
  },
  // Graveler
  {
    stats: { hp: 55, atk: 95, def: 115, spe: 35, spc: 45 },
    types: createTypes(Type.Rock, Type.Ground),
  },
  // Golem
  {
    stats: { hp: 80, atk: 110, def: 130, spe: 45, spc: 55 },
    types: createTypes(Type.Rock, Type.Ground),
  },
  // Ponyta
  {
    stats: { hp: 50, atk: 85, def: 55, spe: 90, spc: 65 },
    types: createTypes(Type.Fire, Type.Fire),
  },
  // Rapidash
  {
    stats: { hp: 65, atk: 100, def: 70, spe: 105, spc: 80 },
    types: createTypes(Type.Fire, Type.Fire),
  },
  // Slowpoke
  {
    stats: { hp: 90, atk: 65, def: 65, spe: 15, spc: 40 },
    types: createTypes(Type.Water, Type.Psychic),
  },
  // Slowbro
  {
    stats: { hp: 95, atk: 75, def: 110, spe: 30, spc: 80 },
    types: createTypes(Type.Water, Type.Psychic),
  },
  // Magnemite
  {
    stats: { hp: 25, atk: 35, def: 70, spe: 45, spc: 95 },
    types: createTypes(Type.Electric, Type.Electric),
  },
  // Magneton
  {
    stats: { hp: 50, atk: 60, def: 95, spe: 70, spc: 120 },
    types: createTypes(Type.Electric, Type.Electric),
  },
  // Farfetchd
  {
    stats: { hp: 52, atk: 65, def: 55, spe: 60, spc: 58 },
    types: createTypes(Type.Normal, Type.Flying),
  },
  // Doduo
  {
    stats: { hp: 35, atk: 85, def: 45, spe: 75, spc: 35 },
    types: createTypes(Type.Normal, Type.Flying),
  },
  // Dodrio
  {
    stats: { hp: 60, atk: 110, def: 70, spe: 100, spc: 60 },
    types: createTypes(Type.Normal, Type.Flying),
  },
  // Seel
  {
    stats: { hp: 65, atk: 45, def: 55, spe: 45, spc: 70 },
    types: createTypes(Type.Water, Type.Water),
  },
  // Dewgong
  {
    stats: { hp: 90, atk: 70, def: 80, spe: 70, spc: 95 },
    types: createTypes(Type.Water, Type.Ice),
  },
  // Grimer
  {
    stats: { hp: 80, atk: 80, def: 50, spe: 25, spc: 40 },
    types: createTypes(Type.Poison, Type.Poison),
  },
  // Muk
  {
    stats: { hp: 105, atk: 105, def: 75, spe: 50, spc: 65 },
    types: createTypes(Type.Poison, Type.Poison),
  },
  // Shellder
  {
    stats: { hp: 30, atk: 65, def: 100, spe: 40, spc: 45 },
    types: createTypes(Type.Water, Type.Water),
  },
  // Cloyster
  {
    stats: { hp: 50, atk: 95, def: 180, spe: 70, spc: 85 },
    types: createTypes(Type.Water, Type.Ice),
  },
  // Gastly
  {
    stats: { hp: 30, atk: 35, def: 30, spe: 80, spc: 100 },
    types: createTypes(Type.Ghost, Type.Poison),
  },
  // Haunter
  {
    stats: { hp: 45, atk: 50, def: 45, spe: 95, spc: 115 },
    types: createTypes(Type.Ghost, Type.Poison),
  },
  // Gengar
  {
    stats: { hp: 60, atk: 65, def: 60, spe: 110, spc: 130 },
    types: createTypes(Type.Ghost, Type.Poison),
  },
  // Onix
  {
    stats: { hp: 35, atk: 45, def: 160, spe: 70, spc: 30 },
    types: createTypes(Type.Rock, Type.Ground),
  },
  // Drowzee
  {
    stats: { hp: 60, atk: 48, def: 45, spe: 42, spc: 90 },
    types: createTypes(Type.Psychic, Type.Psychic),
  },
  // Hypno
  {
    stats: { hp: 85, atk: 73, def: 70, spe: 67, spc: 115 },
    types: createTypes(Type.Psychic, Type.Psychic),
  },
  // Krabby
  {
    stats: { hp: 30, atk: 105, def: 90, spe: 50, spc: 25 },
    types: createTypes(Type.Water, Type.Water),
  },
  // Kingler
  {
    stats: { hp: 55, atk: 130, def: 115, spe: 75, spc: 50 },
    types: createTypes(Type.Water, Type.Water),
  },
  // Voltorb
  {
    stats: { hp: 40, atk: 30, def: 50, spe: 100, spc: 55 },
    types: createTypes(Type.Electric, Type.Electric),
  },
  // Electrode
  {
    stats: { hp: 60, atk: 50, def: 70, spe: 140, spc: 80 },
    types: createTypes(Type.Electric, Type.Electric),
  },
  // Exeggcute
  {
    stats: { hp: 60, atk: 40, def: 80, spe: 40, spc: 60 },
    types: createTypes(Type.Grass, Type.Psychic),
  },
  // Exeggutor
  {
    stats: { hp: 95, atk: 95, def: 85, spe: 55, spc: 125 },
    types: createTypes(Type.Grass, Type.Psychic),
  },
  // Cubone
  {
    stats: { hp: 50, atk: 50, def: 95, spe: 35, spc: 40 },
    types: createTypes(Type.Ground, Type.Ground),
  },
  // Marowak
  {
    stats: { hp: 60, atk: 80, def: 110, spe: 45, spc: 50 },
    types: createTypes(Type.Ground, Type.Ground),
  },
  // Hitmonlee
  {
    stats: { hp: 50, atk: 120, def: 53, spe: 87, spc: 35 },
    types: createTypes(Type.Fighting, Type.Fighting),
  },
  // Hitmonchan
  {
    stats: { hp: 50, atk: 105, def: 79, spe: 76, spc: 35 },
    types: createTypes(Type.Fighting, Type.Fighting),
  },
  // Lickitung
  {
    stats: { hp: 90, atk: 55, def: 75, spe: 30, spc: 60 },
    types: createTypes(Type.Normal, Type.Normal),
  },
  // Koffing
  {
    stats: { hp: 40, atk: 65, def: 95, spe: 35, spc: 60 },
    types: createTypes(Type.Poison, Type.Poison),
  },
  // Weezing
  {
    stats: { hp: 65, atk: 90, def: 120, spe: 60, spc: 85 },
    types: createTypes(Type.Poison, Type.Poison),
  },
  // Rhyhorn
  {
    stats: { hp: 80, atk: 85, def: 95, spe: 25, spc: 30 },
    types: createTypes(Type.Ground, Type.Rock),
  },
  // Rhydon
  {
    stats: { hp: 105, atk: 130, def: 120, spe: 40, spc: 45 },
    types: createTypes(Type.Ground, Type.Rock),
  },
  // Chansey
  {
    stats: { hp: 250, atk: 5, def: 5, spe: 50, spc: 105 },
    types: createTypes(Type.Normal, Type.Normal),
  },
  // Tangela
  {
    stats: { hp: 65, atk: 55, def: 115, spe: 60, spc: 100 },
    types: createTypes(Type.Grass, Type.Grass),
  },
  // Kangaskhan
  {
    stats: { hp: 105, atk: 95, def: 80, spe: 90, spc: 40 },
    types: createTypes(Type.Normal, Type.Normal),
  },
  // Horsea
  {
    stats: { hp: 30, atk: 40, def: 70, spe: 60, spc: 70 },
    types: createTypes(Type.Water, Type.Water),
  },
  // Seadra
  {
    stats: { hp: 55, atk: 65, def: 95, spe: 85, spc: 95 },
    types: createTypes(Type.Water, Type.Water),
  },
  // Goldeen
  {
    stats: { hp: 45, atk: 67, def: 60, spe: 63, spc: 50 },
    types: createTypes(Type.Water, Type.Water),
  },
  // Seaking
  {
    stats: { hp: 80, atk: 92, def: 65, spe: 68, spc: 80 },
    types: createTypes(Type.Water, Type.Water),
  },
  // Staryu
  {
    stats: { hp: 30, atk: 45, def: 55, spe: 85, spc: 70 },
    types: createTypes(Type.Water, Type.Water),
  },
  // Starmie
  {
    stats: { hp: 60, atk: 75, def: 85, spe: 115, spc: 100 },
    types: createTypes(Type.Water, Type.Psychic),
  },
  // MrMime
  {
    stats: { hp: 40, atk: 45, def: 65, spe: 90, spc: 100 },
    types: createTypes(Type.Psychic, Type.Psychic),
  },
  // Scyther
  {
    stats: { hp: 70, atk: 110, def: 80, spe: 105, spc: 55 },
    types: createTypes(Type.Bug, Type.Flying),
  },
  // Jynx
  {
    stats: { hp: 65, atk: 50, def: 35, spe: 95, spc: 95 },
    types: createTypes(Type.Ice, Type.Psychic),
  },
  // Electabuzz
  {
    stats: { hp: 65, atk: 83, def: 57, spe: 105, spc: 85 },
    types: createTypes(Type.Electric, Type.Electric),
  },
  // Magmar
  {
    stats: { hp: 65, atk: 95, def: 57, spe: 93, spc: 85 },
    types: createTypes(Type.Fire, Type.Fire),
  },
  // Pinsir
  {
    stats: { hp: 65, atk: 125, def: 100, spe: 85, spc: 55 },
    types: createTypes(Type.Bug, Type.Bug),
  },
  // Tauros
  {
    stats: { hp: 75, atk: 100, def: 95, spe: 110, spc: 70 },
    types: createTypes(Type.Normal, Type.Normal),
  },
  // Magikarp
  {
    stats: { hp: 20, atk: 10, def: 55, spe: 80, spc: 20 },
    types: createTypes(Type.Water, Type.Water),
  },
  // Gyarados
  {
    stats: { hp: 95, atk: 125, def: 79, spe: 81, spc: 100 },
    types: createTypes(Type.Water, Type.Flying),
  },
  // Lapras
  {
    stats: { hp: 130, atk: 85, def: 80, spe: 60, spc: 95 },
    types: createTypes(Type.Water, Type.Ice),
  },
  // Ditto
  {
    stats: { hp: 48, atk: 48, def: 48, spe: 48, spc: 48 },
    types: createTypes(Type.Normal, Type.Normal),
  },
  // Eevee
  {
    stats: { hp: 55, atk: 55, def: 50, spe: 55, spc: 65 },
    types: createTypes(Type.Normal, Type.Normal),
  },
  // Vaporeon
  {
    stats: { hp: 130, atk: 65, def: 60, spe: 65, spc: 110 },
    types: createTypes(Type.Water, Type.Water),
  },
  // Jolteon
  {
    stats: { hp: 65, atk: 65, def: 60, spe: 130, spc: 110 },
    types: createTypes(Type.Electric, Type.Electric),
  },
  // Flareon
  {
    stats: { hp: 65, atk: 130, def: 60, spe: 65, spc: 110 },
    types: createTypes(Type.Fire, Type.Fire),
  },
  // Porygon
  {
    stats: { hp: 65, atk: 60, def: 70, spe: 40, spc: 75 },
    types: createTypes(Type.Normal, Type.Normal),
  },
  // Omanyte
  {
    stats: { hp: 35, atk: 40, def: 100, spe: 35, spc: 90 },
    types: createTypes(Type.Rock, Type.Water),
  },
  // Omastar
  {
    stats: { hp: 70, atk: 60, def: 125, spe: 55, spc: 115 },
    types: createTypes(Type.Rock, Type.Water),
  },
  // Kabuto
  {
    stats: { hp: 30, atk: 80, def: 90, spe: 55, spc: 45 },
    types: createTypes(Type.Rock, Type.Water),
  },
  // Kabutops
  {
    stats: { hp: 60, atk: 115, def: 105, spe: 80, spc: 70 },
    types: createTypes(Type.Rock, Type.Water),
  },
  // Aerodactyl
  {
    stats: { hp: 80, atk: 105, def: 65, spe: 130, spc: 60 },
    types: createTypes(Type.Rock, Type.Flying),
  },
  // Snorlax
  {
    stats: { hp: 160, atk: 110, def: 65, spe: 30, spc: 65 },
    types: createTypes(Type.Normal, Type.Normal),
  },
  // Articuno
  {
    stats: { hp: 90, atk: 85, def: 100, spe: 85, spc: 125 },
    types: createTypes(Type.Ice, Type.Flying),
  },
  // Zapdos
  {
    stats: { hp: 90, atk: 90, def: 85, spe: 100, spc: 125 },
    types: createTypes(Type.Electric, Type.Flying),
  },
  // Moltres
  {
    stats: { hp: 90, atk: 100, def: 90, spe: 90, spc: 125 },
    types: createTypes(Type.Fire, Type.Flying),
  },
  // Dratini
  {
    stats: { hp: 41, atk: 64, def: 45, spe: 50, spc: 50 },
    types: createTypes(Type.Dragon, Type.Dragon),
  },
  // Dragonair
  {
    stats: { hp: 61, atk: 84, def: 65, spe: 70, spc: 70 },
    types: createTypes(Type.Dragon, Type.Dragon),
  },
  // Dragonite
  {
    stats: { hp: 91, atk: 134, def: 95, spe: 80, spc: 100 },
    types: createTypes(Type.Dragon, Type.Flying),
  },
  // Mewtwo
  {
    stats: { hp: 106, atk: 110, def: 90, spe: 130, spc: 154 },
    types: createTypes(Type.Psychic, Type.Psychic),
  },
  // Mew
  {
    stats: { hp: 100, atk: 100, def: 100, spe: 100, spc: 100 },
    types: createTypes(Type.Psychic, Type.Psychic),
  },
];

// Constants and utility functions
export const size = 151; // The number of Pokémon species in this generation

/**
 * The Pokémon's critical hit ratio out of 256.
 */
export function chance(id: Species): number {
  if (id === Species.None) {
    throw new Error("Invalid species ID");
  }
  return CHANCES[id - 1];
}

/**
 * Returns the data corresponding to the species.
 */
export function get(id: Species): SpeciesData {
  if (id === Species.None) {
    throw new Error("Invalid species ID");
  }
  return DATA[id - 1];
}
